-- 코드를 입력하세요
SELECT MILK.CART_ID FROM (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Milk') AS MILK
INNER JOIN (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Yogurt') AS YOGURT
ON MILK.CART_ID = YOGURT.CART_ID
ORDER BY MILK.CART_ID