-- 코드를 입력하세요
SELECT PLACES.*
FROM PLACES 
INNER JOIN 
(SELECT HOST_ID, COUNT(ID) AS ID_CNT
FROM PLACES
GROUP BY HOST_ID
HAVING ID_CNT >= 2) AS HEAVY_USERS
ON PLACES.HOST_ID = HEAVY_USERS.HOST_ID
ORDER BY PLACES.ID