-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES FROM
(SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, FOOD_PRODUCT.PRICE, FOOD_ORDER.AMOUNT
FROM FOOD_PRODUCT
RIGHT JOIN FOOD_ORDER
ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE MONTH(FOOD_ORDER.PRODUCE_DATE) = 5 AND YEAR(FOOD_ORDER.PRODUCE_DATE) = 2022) AS PRODUCT_TOTAL
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID