-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID,ANIMAL_OUTS.ANIMAL_TYPE,ANIMAL_OUTS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male') 
AND ANIMAL_INS.SEX_UPON_INTAKE NOT IN ('Spayed Female', 'Neutered Male') 
ORDER BY ANIMAL_OUTS.ANIMAL_ID