-- 코드를 작성해주세요
SELECT DEVELOPERS.ID, DEVELOPERS.EMAIL, DEVELOPERS.FIRST_NAME, DEVELOPERS.LAST_NAME FROM (SELECT * 
FROM DEVELOPERS,(SELECT SUM(CODE) AS SUM_CODE FROM SKILLCODES 
GROUP BY CATEGORY
HAVING CATEGORY = 'Front End') FRONT_END) DEVELOPERS 
WHERE DEVELOPERS.SUM_CODE & SKILL_CODE <> 0
ORDER BY DEVELOPERS.ID 