-- 코드를 입력하세요
SELECT MEMBER_INFO.MEMBER_NAME,REST_REVIEW.REVIEW_TEXT, DATE_FORMAT(REST_REVIEW.REVIEW_DATE,"%Y-%m-%d") REVIEW_DATE FROM (SELECT MEMBER_PROFILE.MEMBER_ID,MEMBER_PROFILE.MEMBER_NAME  FROM 
(SELECT MEMBER_ID, COUNT(REVIEW_ID) AS COUNT_REVIEW
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT_REVIEW DESC
LIMIT 1) AS BEST_REVIEW
INNER JOIN MEMBER_PROFILE
ON BEST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID) AS MEMBER_INFO
INNER JOIN REST_REVIEW
ON MEMBER_INFO.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT