-- 코드를 작성해주세요
SELECT ECOLI_DATA.ID, COUNT(CHILD_DATA.ID) AS CHILD_COUNT
FROM ECOLI_DATA 
LEFT JOIN ECOLI_DATA AS CHILD_DATA
ON ECOLI_DATA.ID = CHILD_DATA.PARENT_ID
GROUP BY ECOLI_DATA.ID
ORDER BY ECOLI_DATA.ID