-- 코드를 입력하세요
SELECT MONTH_CARS.*
FROM (SELECT MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, HISTORY_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10)
MONTH_CARS
GROUP BY MONTH, CAR_ID) AS MONTH_CARS
INNER JOIN (SELECT CAR_ID, COUNT(HISTORY_ID) AS COUNTS
FROM (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, HISTORY_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10) AS CONDITION_COUNTS
GROUP BY CAR_ID
HAVING COUNTS >= 5) AS CONDITION_COUNTS
ON CONDITION_COUNTS.CAR_ID = MONTH_CARS.CAR_ID
ORDER BY MONTH, CAR_ID DESC

