-- 코드를 입력하세요
SELECT *
FROM(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,PRODUCT_ID,USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
UNION
SELECT  DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, 
CASE 
WHEN OFFLINE_SALE_ID THEN NULL
END
AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE) AS SALES_ENTIRE
WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID