-- 코드를 입력하세요
SELECT * FROM (SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE, ROUND((CAR_RENTAL_COMPANY_CAR.DAILY_FEE * (100-CAR_DURATION.DISCOUNT_RATE) * 0.3),0) AS FEE FROM CAR_RENTAL_COMPANY_CAR
INNER JOIN(SELECT CAR_TYPE,DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE IN ('SUV','세단')) AS CAR_DURATION
ON CAR_RENTAL_COMPANY_CAR.CAR_TYPE = CAR_DURATION.CAR_TYPE
WHERE CAR_ID NOT IN 
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
GROUP BY CAR_ID)) AS TOTAL
WHERE TOTAL.FEE >= 500000 AND TOTAL.FEE < 2000000
ORDER BY TOTAL.FEE DESC, TOTAL.CAR_TYPE, TOTAL.CAR_ID DESC
