-- 코드를 작성해주세요
SELECT  SUM(HR_GRADE.SCORE) AS SCORE ,HR_EMPLOYEES.EMP_NO, HR_EMPLOYEES.EMP_NAME,HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
FROM HR_EMPLOYEES
INNER JOIN HR_GRADE 
ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
GROUP BY HR_EMPLOYEES.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
