# -- 코드를 작성해주세요
SELECT RANK_ECOLI.ID, CASE
WHEN RANK_SIZE/TOTAL_COUNT <= 0.25 THEN 'CRITICAL'
WHEN RANK_SIZE/TOTAL_COUNT BETWEEN 0.25 AND 0.5 THEN 'HIGH'
WHEN RANK_SIZE/TOTAL_COUNT BETWEEN 0.5 AND 0.75 THEN 'MEDIUM'
WHEN RANK_SIZE/TOTAL_COUNT BETWEEN 0.75 AND 1 THEN 'LOW'
END AS COLONY_NAME
FROM (SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANK_SIZE, CASE
WHEN ID IS NOT NULL THEN (SELECT COUNT(*) FROM ECOLI_DATA)
END AS TOTAL_COUNT
FROM ECOLI_DATA) AS RANK_ECOLI 
ORDER BY RANK_ECOLI.ID