-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, CONCAT(USED_GOODS_USER.CITY," ", USED_GOODS_USER.STREET_ADDRESS1," ", USED_GOODS_USER.STREET_ADDRESS2) AS 전체주소, CONCAT(MID(USED_GOODS_USER.TLNO,1,3),'-',MID(USED_GOODS_USER.TLNO,4,4),'-',MID(USED_GOODS_USER.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER
INNER JOIN (SELECT WRITER_ID, COUNT(BOARD_ID) AS BOARD_CNT FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(BOARD_ID) >= 3) USED_GOODS_BOARD
ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
ORDER BY USED_GOODS_USER.USER_ID DESC
