-- 코드를 입력하세요
SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM(SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, REST_REVIEW.REVIEW_SCORE
FROM REST_INFO
INNER JOIN REST_REVIEW
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE REST_INFO.ADDRESS LIKE '서울%') AS REST_INFO
GROUP BY REST_INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC