SELECT CONCAT_DATA.ROUTE, CONCAT(CONCAT_DATA.TOTAL_DISTANCE,'km') AS TOTAL_DISTANCE,CONCAT(CONCAT_DATA.AVERAGE_DISTANCE,'km') AS AVERAGE_DISTANCE
FROM (
    SELECT ROUTE, ROUND(SUM(D_BETWEEN_DIST),1) AS TOTAL_DISTANCE, ROUND(AVG(D_BETWEEN_DIST),2) AS AVERAGE_DISTANCE
    FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC) AS CONCAT_DATA
;