WITH RECURSIVE PARENT_TREE AS (
SELECT ID, PARENT_ID, 1 AS LEVEL
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, 1+PARENT_TREE.LEVEL AS LEVEL
FROM ECOLI_DATA
INNER JOIN PARENT_TREE
ON PARENT_TREE.ID = ECOLI_DATA.PARENT_ID
)

SELECT COUNT(A.ID) AS COUNT, A.LEVEL AS GENERATION
FROM PARENT_TREE AS A
LEFT JOIN PARENT_TREE AS B
ON A.ID = B.PARENT_ID
WHERE B.ID IS NULL
GROUP BY A.LEVEL
ORDER BY GENERATION