# SELECT PURCHASE_USER.YEAR, PURCHASE_USER.MONTH, COUNT(PURCHASE_USER.USER_ID) AS PUCHASED_USERS
# FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_INFO.USER_ID
# FROM ONLINE_SALE
# INNER JOIN USER_INFO
# ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
# WHERE YEAR(USER_INFO.JOINED) = 2021
# GROUP BY YEAR, MONTH, USER_INFO.USER_ID) AS PURCHASE_USER
# GROUP BY PURCHASE_USER.YEAR, PURCHASE_USER.MONTH

# SELECT PURCHASE_USER.YEAR, PURCHASE_USER.MONTH, PURCHASE_USER.USER_YEAR,COUNT(PURCHASE_USER.USER_ID) AS PUCHASED_USERS
# FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_INFO.USER_ID, YEAR(USER_INFO.JOINED) AS USER_YEAR
# FROM ONLINE_SALE
# INNER JOIN USER_INFO
# ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
# WHERE YEAR(USER_INFO.JOINED) = 2021
# GROUP BY YEAR, MONTH, USER_INFO.USER_ID) AS PURCHASE_USER
# GROUP BY PURCHASE_USER.YEAR, PURCHASE_USER.MONTH

SELECT PURCHASE_USER.YEAR, PURCHASE_USER.MONTH, PURCHASE_USER.PUCHASED_USERS, ROUND(PURCHASE_USER.PUCHASED_USERS/TOTAL_USERS.USER_TOTAL,1) AS PUCHASED_RATIO
FROM (SELECT PURCHASE_USER.YEAR, PURCHASE_USER.MONTH, PURCHASE_USER.USER_YEAR,COUNT(PURCHASE_USER.USER_ID) AS PUCHASED_USERS
FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_INFO.USER_ID, YEAR(USER_INFO.JOINED) AS USER_YEAR
FROM ONLINE_SALE
INNER JOIN USER_INFO
ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE YEAR(USER_INFO.JOINED) = 2021
GROUP BY YEAR, MONTH, USER_INFO.USER_ID) AS PURCHASE_USER
GROUP BY PURCHASE_USER.YEAR, PURCHASE_USER.MONTH) AS PURCHASE_USER
INNER JOIN (SELECT YEAR(JOINED) AS YEAR, COUNT(USER_ID) AS USER_TOTAL
FROM USER_INFO
GROUP BY YEAR) AS TOTAL_USERS
ON TOTAL_USERS.YEAR = PURCHASE_USER.USER_YEAR
ORDER BY PURCHASE_USER.YEAR, PURCHASE_USER.MONTH