-- 코드를 입력하세요
SELECT CAR_ID, CASE
WHEN SUM(CHECK_DATE) = 0 THEN '대여 가능'
ELSE '대여중' END AS AVAILABILITY
FROM (SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,'%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE,'%Y-%m-%d') AS END_DATE, CASE 
WHEN  DATE_FORMAT(END_DATE,'%Y-%m-%d') >= DATE('2022-10-16') AND  DATE_FORMAT(START_DATE,'%Y-%m-%d') <= DATE('2022-10-16') THEN 1
ELSE 0
END AS CHECK_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC