-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, BOOK.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM (SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, BOOK.BOOK_ID, BOOK.PRICE
FROM BOOK
INNER JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID) AS BOOK
INNER JOIN (SELECT * FROM BOOK_SALES
WHERE YEAR(BOOK_SALES.SALES_DATE) = 2022 AND MONTH(BOOK_SALES.SALES_DATE) = 1) AS BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC