-- 코드를 입력하세요
SELECT CAR_DATE.CAR_ID, ROUND(SUM(CAR_DATE.DATEDIFF)/ COUNT(CAR_DATE.DATEDIFF),1) AS AVERAGE_DURATION
FROM(SELECT *, DATEDIFF(DATE_FORMAT(END_DATE,"%Y-%m-%d"),DATE_FORMAT(START_DATE,"%Y-%m-%d"))+1 AS DATEDIFF
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)CAR_DATE
GROUP BY CAR_DATE.CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_DATE.CAR_ID DESC