-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, SUM(USED_GOODS_BOARD.PRICE) AS TOTAL_SALES
FROM (SELECT WRITER_ID, PRICE FROM USED_GOODS_BOARD  WHERE STATUS = 'DONE') AS USED_GOODS_BOARD 
INNER JOIN (SELECT USER_ID, NICKNAME FROM USED_GOODS_USER) AS USED_GOODS_USER 
ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
GROUP BY USED_GOODS_USER.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES