-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',USED_GOODS_FILE.BOARD_ID,'/',USED_GOODS_FILE.FILE_ID,USED_GOODS_FILE.FILE_NAME,USED_GOODS_FILE.FILE_EXT ) AS FILE_PATH
FROM USED_GOODS_FILE
INNER JOIN (SELECT *
FROM USED_GOODS_BOARD 
ORDER BY VIEWS DESC
LIMIT 1) BEST_VIEW
ON BEST_VIEW.BOARD_ID = USED_GOODS_FILE.BOARD_ID
ORDER BY USED_GOODS_FILE.FILE_ID DESC