-- 코드를 입력하세요
SELECT APPOINTMENT.APNT_NO, APPOINTMENT.PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DOCTOR.DR_NAME, APPOINTMENT.APNT_YMD FROM
(SELECT APPOINTMENT.APNT_NO, PATIENT.PT_NAME, PATIENT.PT_NO, APPOINTMENT.MCDP_CD, APPOINTMENT.APNT_YMD, APPOINTMENT.MDDR_ID
FROM PATIENT 
INNER JOIN APPOINTMENT 
ON PATIENT.PT_NO = APPOINTMENT.PT_NO
WHERE DATE(APPOINTMENT.APNT_YMD) = '2022-04-13' AND APPOINTMENT.APNT_CNCL_YMD IS NULL AND APPOINTMENT.MCDP_CD = 'CS') AS APPOINTMENT
INNER JOIN DOCTOR
ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
ORDER BY APPOINTMENT.APNT_YMD