-- 코드를 작성해주세요
SELECT * FROM (SELECT
CASE 
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AND SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#' ) THEN 'B'
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End' ) THEN 'C'
END GRADE, ID, EMAIL
FROM DEVELOPERS ) GRADE_CODE
WHERE GRADE_CODE.GRADE IS NOT NULL
ORDER BY GRADE_CODE.GRADE, GRADE_CODE.ID