-- 코드를 작성해주세요
SELECT EXOLI_DATA.YEAR, (YEAR_MAX_DATA.MAX_SIZE - EXOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV,EXOLI_DATA.ID
FROM (SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA ) AS EXOLI_DATA
INNER JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR_MAX,MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA 
GROUP BY YEAR_MAX) AS YEAR_MAX_DATA
ON YEAR_MAX_DATA.YEAR_MAX = EXOLI_DATA.YEAR
ORDER BY EXOLI_DATA.YEAR, YEAR_DEV