-- 코드를 입력하세요
SELECT YEAR_PT.MCDP_CD AS 진료과코드, COUNT(YEAR_PT.PT_NO) AS 5월예약건수
FROM (SELECT * 
      FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 5)
AS YEAR_PT
GROUP BY YEAR_PT.MCDP_CD
ORDER BY 5월예약건수, 진료과코드