-- 코드를 입력하세요
SELECT DISTINCT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
FROM(SELECT *
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE = '세단') AS CAR_RENTAL_COMPANY_CAR 
INNER JOIN (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE MONTH(START_DATE) = 10) AS CAR_RENTAL_COMPANY_RENTAL_HISTORY 
ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC