-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM REST_INFO
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) AS MAX_FOOD_TYPE
ON REST_INFO.FOOD_TYPE = MAX_FOOD_TYPE.FOOD_TYPE
WHERE REST_INFO.FAVORITES = MAX_FOOD_TYPE.MAX_FAVORITES
ORDER BY REST_INFO.FOOD_TYPE DESC