-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_TREE
LEFT JOIN ITEM_TREE AS PARENT_ITEM
ON ITEM_TREE.ITEM_ID = PARENT_ITEM.PARENT_ITEM_ID
LEFT JOIN ITEM_INFO
ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
WHERE PARENT_ITEM.ITEM_ID IS NULL
ORDER BY ITEM_INFO.ITEM_ID DESC