# -- 코드를 작성해주세요
SELECT FISH_INFO.ID, FISH_NAME_INFO.FISH_NAME, FISH_INFO.LENGTH
FROM (SELECT FISH_INFO.ID, FISH_INFO.LENGTH, MAX_LENGTH.FISH_TYPE
FROM FISH_INFO
INNER JOIN (SELECT FISH_INFO.FISH_TYPE, MAX(FISH_INFO.LENGTH) AS LENGTH
FROM FISH_NAME_INFO 
INNER JOIN FISH_INFO
ON FISH_INFO.FISH_TYPE= FISH_NAME_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_TYPE) MAX_LENGTH
ON MAX_LENGTH.FISH_TYPE = FISH_INFO.FISH_TYPE
WHERE MAX_LENGTH.LENGTH = FISH_INFO.LENGTH) FISH_INFO
INNER JOIN FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY FISH_INFO.ID