-- 코드를 작성해주세요
SELECT THIRD_PARENT.ID
FROM (SELECT SECOND_PARENT.ID
FROM (SELECT ID FROM ECOLI_DATA
WHERE ECOLI_DATA.PARENT_ID IS NULL)
AS FIRST_PARENT
INNER JOIN ECOLI_DATA AS SECOND_PARENT
ON FIRST_PARENT.ID = SECOND_PARENT.PARENT_ID) AS SECOND_PARENT
INNER JOIN ECOLI_DATA AS THIRD_PARENT
ON SECOND_PARENT.ID = THIRD_PARENT.PARENT_ID
ORDER BY THIRD_PARENT.ID