SELECT BOOK.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE YEAR(BOOK_SALES.SALES_DATE) = 2022 AND MONTH(BOOK_SALES.SALES_DATE) = 1
GROUP BY BOOK_ID) AS BOOK_SALES
INNER JOIN BOOK
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY