# -- 코드를 입력하세요
# SELECT PRICE_LIST.CATEGORY,PRICE_LIST.PRICE AS MAX_PRICE, PRICE_LIST.PRODUCT_NAME
# FROM () AS PRICE_LIST
# GROUP BY PRICE_LIST.CATEGORY
# HAVING PRICE_LIST.CATEGORY IN ('과자','국','김치','식용유')
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (SELECT * FROM FOOD_PRODUCT
WHERE CATEGORY = '과자'
ORDER BY PRICE DESC
LIMIT 1) AS MAX_SNACK
UNION
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM(SELECT * FROM FOOD_PRODUCT
WHERE CATEGORY = '국'
ORDER BY PRICE DESC
LIMIT 1) AS MAX_SOUP
UNION 
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM(SELECT * FROM FOOD_PRODUCT
WHERE CATEGORY = '김치'
ORDER BY PRICE DESC
LIMIT 1) AS MAX_KIMCHI
UNION
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM(SELECT * FROM FOOD_PRODUCT
WHERE CATEGORY = '식용유'
ORDER BY PRICE DESC
LIMIT 1) AS MAX_OIL
ORDER BY MAX_PRICE DESC