-- 코드를 입력하세요
SELECT TOTAL.FLAVOR FROM (
SELECT FIRST_HALF.FLAVOR, (FIRST_HALF.TOTAL_ORDER + JULY.TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF
GROUP BY FLAVOR) AS FIRST_HALF
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) AS JULY
ON FIRST_HALF.FLAVOR = JULY.FLAVOR) TOTAL
ORDER BY TOTAL.TOTAL_ORDER DESC
LIMIT 3